DROP DATABASE IF EXISTS lab2023;
CREATE DATABASE lab2023;
USE lab2023;

CREATE TABLE User
(
  User_id INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL,
  Last_name VARCHAR(50) NOT NULL,
  Email VARCHAR(50) NOT NULL UNIQUE,
  Password VARCHAR(100) NOT NULL,
  Carreer VARCHAR(50) NOT NULL,
  Year INT NOT NULL,
  Magister VARCHAR(5) NOT NULL,
  Hash_user VARCHAR(100) NOT NULL,
  PRIMARY KEY (User_id)
);

CREATE TABLE Attendance
(
  Attendance_id INT NOT NULL AUTO_INCREMENT,
  Entry_date DATETIME NOT NULL,
  Exit_date DATETIME  NOT NULL,
  Hash_user VARCHAR(100) NOT NULL,
  PRIMARY KEY (Attendance_id)
  
);

CREATE TABLE Cam_discrepancy
(
  Cam_discrepancy_id INT NOT NULL AUTO_INCREMENT,
  Date DATE NOT NULL,
  Qr_count INT NOT NULL,
  Cam_count INT NOT NULL,
  PRIMARY KEY (Cam_discrepancy_id)
);